### ISSUE TITLE
Discord crash after running

### ISSUE THREAD

**Issue by WaffeldotDev** [NotFubukIl/DiscordTokenGrabber#4]
https://img.waffel.dev/Discord_VJvQUlDsp0 
idk what this means so here is a image of the error. Pls help xD

**Comment by TaxMachine** [comment]
The free grabber doesn't work, please buy it on the discord server or wait for an eventual free version that is currently planned

**Comment by NotFubukIl** [comment]
fixed btw

**Comment by CollabVMA50** [comment]
No dont use this skid grabber
